export enum TypeFileDetail {
  UPLOAD_COMITE_FILE = 0,
  CHECK_COMITE_FILES,
  UPLOAD_FORMATO,
  CHECK_FORMATO,
  CHECK_DOCUMENTACION,
  UPLOAD_DOCUMENTACION,
  UPLOAD_SIMPLE_FILE,
  UPLOAD_VERIFICACION,
  ONLY_VIEW,
}
