export * from './http.response.model';
export * from './user.model';
export * from './dependencia.model';
export * from './comite.model';
export * from './api.model';
export * from './detailFile.model';
export * from './formato.model';
export * from './recomendacion.model';
export * from './documentacion.model';
export * from './queja.model';
export * from './sesion.model';
export * from './general.model';
export * from './evidencia.model';
export * from './notificacion.model';
export * from './chart.model'
